/*COLOCAR INSERTS EN CASO DE SER NECEARIO PARA HACER PRUEBAS */

 INSERT INTO i18n_equipo VALUES ( '1', 'Espanol', 'Argentina' );
 INSERT INTO i18n_equipo VALUES ( '2', 'Espanol', 'Australia' );
 INSERT INTO i18n_equipo VALUES ( '3', 'Espanol', 'Belgica' );
 INSERT INTO i18n_equipo VALUES ( '4', 'Espanol', 'Brasil' );
 INSERT INTO i18n_equipo VALUES ( '5', 'Espanol', 'Colombia' );
 INSERT INTO i18n_equipo VALUES ( '6', 'Espanol', 'Costa Rica' );
 INSERT INTO i18n_equipo VALUES ( '7', 'Espanol', 'Croacia' );
 INSERT INTO i18n_equipo VALUES ( '8', 'Espanol', 'Dinamarca' );
 INSERT INTO i18n_equipo VALUES ( '9', 'Espanol', 'Egypto' );
 INSERT INTO i18n_equipo VALUES ( '10', 'Espanol', 'Inglaterra' );
 INSERT INTO i18n_equipo VALUES ( '11', 'Espanol', 'España' );
 INSERT INTO i18n_equipo VALUES ( '12', 'Espanol', 'Francia' );
 INSERT INTO i18n_equipo VALUES ( '13', 'Espanol', 'Alemania' );
 INSERT INTO i18n_equipo VALUES ( '14', 'Espanol', 'Iran' );
 INSERT INTO i18n_equipo VALUES ( '15', 'Espanol', 'Islandia' );
 INSERT INTO i18n_equipo VALUES ( '16', 'Espanol', 'Japon' );
 INSERT INTO i18n_equipo VALUES ( '17', 'Espanol', 'Korea' );
 INSERT INTO i18n_equipo VALUES ( '18', 'Espanol', 'Arabia Saudita' );
 INSERT INTO i18n_equipo VALUES ( '19', 'Espanol', 'Marruecos' );
 INSERT INTO i18n_equipo VALUES ( '20', 'Espanol', 'Mexico' );
 INSERT INTO i18n_equipo VALUES ( '21', 'Espanol', 'Nigeria' );
 INSERT INTO i18n_equipo VALUES ( '22', 'Espanol', 'Panama' );
 INSERT INTO i18n_equipo VALUES ( '23', 'Espanol', 'Peru' );
 INSERT INTO i18n_equipo VALUES ( '24', 'Espanol', 'Polonia' );
 INSERT INTO i18n_equipo VALUES ( '25', 'Espanol', 'Portugal' );
 INSERT INTO i18n_equipo VALUES ( '26', 'Espanol', 'Rusia' );
 INSERT INTO i18n_equipo VALUES ( '27', 'Espanol', 'Senegal' );
 INSERT INTO i18n_equipo VALUES ( '28', 'Espanol', 'Serbia' );
 INSERT INTO i18n_equipo VALUES ( '29', 'Espanol', 'Suiza' );
 INSERT INTO i18n_equipo VALUES ( '30', 'Espanol', 'Suecia' );
 INSERT INTO i18n_equipo VALUES ( '31', 'Espanol', 'Tunez' );
 INSERT INTO i18n_equipo VALUES ( '32', 'Espanol', 'Uruguay' );
 INSERT INTO i18n_equipo VALUES ( '1', 'English', 'Argentina' );
 INSERT INTO i18n_equipo VALUES ( '2', 'English', 'Australia' );
 INSERT INTO i18n_equipo VALUES ( '3', 'English', 'Belgium' );
 INSERT INTO i18n_equipo VALUES ( '4', 'English', 'Brazil' );
 INSERT INTO i18n_equipo VALUES ( '5', 'English', 'Colombia' );
 INSERT INTO i18n_equipo VALUES ( '6', 'English', 'Costa Rica' );
 INSERT INTO i18n_equipo VALUES ( '7', 'English', 'Croatia' );
 INSERT INTO i18n_equipo VALUES ( '8', 'English', 'Denmark' );
 INSERT INTO i18n_equipo VALUES ( '9', 'English', 'Egypt' );
 INSERT INTO i18n_equipo VALUES ( '10', 'English', 'England' );
 INSERT INTO i18n_equipo VALUES ( '11', 'English', 'Spaid' );
 INSERT INTO i18n_equipo VALUES ( '12', 'English', 'France' );
 INSERT INTO i18n_equipo VALUES ( '13', 'English', 'Germany' );
 INSERT INTO i18n_equipo VALUES ( '14', 'English', 'Iran' );
 INSERT INTO i18n_equipo VALUES ( '15', 'English', 'Iceland' );
 INSERT INTO i18n_equipo VALUES ( '16', 'English', 'Japan' );
 INSERT INTO i18n_equipo VALUES ( '17', 'English', 'Korea' );
 INSERT INTO i18n_equipo VALUES ( '18', 'English', 'Saudi Arabia' );
 INSERT INTO i18n_equipo VALUES ( '19', 'English', 'Morocco' );
 INSERT INTO i18n_equipo VALUES ( '20', 'English', 'Mexico' );
 INSERT INTO i18n_equipo VALUES ( '21', 'English', 'Nigeria' );
 INSERT INTO i18n_equipo VALUES ( '22', 'English', 'Panama' );
 INSERT INTO i18n_equipo VALUES ( '23', 'English', 'Peru' );
 INSERT INTO i18n_equipo VALUES ( '24', 'English', 'Poland' );
 INSERT INTO i18n_equipo VALUES ( '25', 'English', 'Portugal' );
 INSERT INTO i18n_equipo VALUES ( '26', 'English', 'Russia' );
 INSERT INTO i18n_equipo VALUES ( '27', 'English', 'Senegal' );
 INSERT INTO i18n_equipo VALUES ( '28', 'English', 'Serbia' );
 INSERT INTO i18n_equipo VALUES ( '29', 'English', 'Switzerland' );
 INSERT INTO i18n_equipo VALUES ( '30', 'English', 'Sweden' );
 INSERT INTO i18n_equipo VALUES ( '31', 'English', 'Tunisia' );
 INSERT INTO i18n_equipo VALUES ( '32', 'English', 'Uruguay' );


 
 INSERT INTO PAIS VALUES ( 'ARG', '1', '' );
 INSERT INTO PAIS VALUES ( 'AUS', '2', '' );
 INSERT INTO PAIS VALUES ( 'BEL', '3', '' );
 INSERT INTO PAIS VALUES ( 'BRA', '4', '' );
 INSERT INTO PAIS VALUES ( 'COL', '5', '' );
 INSERT INTO PAIS VALUES ( 'CRC', '6', '' );
 INSERT INTO PAIS VALUES ( 'CRO', '7', '' );
 INSERT INTO PAIS VALUES ( 'DEN', '8', '' );
 INSERT INTO PAIS VALUES ( 'EGY', '9', '' );
 INSERT INTO PAIS VALUES ( 'END', '10', '' );
 INSERT INTO PAIS VALUES ( 'ESP', '11', '' );
 INSERT INTO PAIS VALUES ( 'FRA', '12', '' );
 INSERT INTO PAIS VALUES ( 'GER', '13', '' );
 INSERT INTO PAIS VALUES ( 'IRN', '14', '' );
 INSERT INTO PAIS VALUES ( 'ISL', '15', '' );
 INSERT INTO PAIS VALUES ( 'JPN', '16', '' );
 INSERT INTO PAIS VALUES ( 'KON', '17', '' );
 INSERT INTO PAIS VALUES ( 'KSA', '18', '' );
 INSERT INTO PAIS VALUES ( 'MAR', '19', '' );
 INSERT INTO PAIS VALUES ( 'MEX', '20', '' );
 INSERT INTO PAIS VALUES ( 'NGA', '21', '' );
 INSERT INTO PAIS VALUES ( 'PAN', '22', '' );
 INSERT INTO PAIS VALUES ( 'PER', '23', '' );
 INSERT INTO PAIS VALUES ( 'POL', '24', '' );
 INSERT INTO PAIS VALUES ( 'POR', '25', '' );
 INSERT INTO PAIS VALUES ( 'RUS', '26', '' );
 INSERT INTO PAIS VALUES ( 'SEN', '27', '' );
 INSERT INTO PAIS VALUES ( 'SRB', '28', '' );
 INSERT INTO PAIS VALUES ( 'SUI', '29', '' );
 INSERT INTO PAIS VALUES ( 'SWE', '30', '' );
 INSERT INTO PAIS VALUES ( 'TUN', '31', '' );
 INSERT INTO PAIS VALUES ( 'URU', '32', '' );

