/*COLOCAR INSERTS EN CASO DE SER NECEARIO PARA HACER PRUEBAS */

 INSERT INTO i18n_equipo VALUES ( '1', '1', 'es', 'Argentina' );
 INSERT INTO i18n_equipo VALUES ( '2', '2', 'es', 'Australia' );
 INSERT INTO i18n_equipo VALUES ( '3', '3', 'es', 'Belgica' );
 INSERT INTO i18n_equipo VALUES ( '4', '4', 'es', 'Brasil' );
 INSERT INTO i18n_equipo VALUES ( '5', '5', 'es', 'Colombia' );
 INSERT INTO i18n_equipo VALUES ( '6', '6', 'es', 'Costa Rica' );
 INSERT INTO i18n_equipo VALUES ( '7', '7', 'es', 'Croacia' );
 INSERT INTO i18n_equipo VALUES ( '8', '8', 'es', 'Dinamarca' );
 INSERT INTO i18n_equipo VALUES ( '9', '9', 'es', 'Egypto' );
 INSERT INTO i18n_equipo VALUES ( '10', '10', 'es', 'Inglaterra' );
 INSERT INTO i18n_equipo VALUES ( '11', '11', 'es', 'España' );
 INSERT INTO i18n_equipo VALUES ( '12', '12', 'es', 'Francia' );
 INSERT INTO i18n_equipo VALUES ( '13', '13', 'es', 'Alemania' );
 INSERT INTO i18n_equipo VALUES ( '14', '14', 'es', 'Iran' );
 INSERT INTO i18n_equipo VALUES ( '15', '15', 'es', 'Islandia' );
 INSERT INTO i18n_equipo VALUES ( '16', '16', 'es', 'Japon' );
 INSERT INTO i18n_equipo VALUES ( '17', '17', 'es', 'Korea' );
 INSERT INTO i18n_equipo VALUES ( '18', '18', 'es', 'Arabia Saudita' );
 INSERT INTO i18n_equipo VALUES ( '19', '19', 'es', 'Marruecos' );
 INSERT INTO i18n_equipo VALUES ( '20', '20', 'es', 'Mexico' );
 INSERT INTO i18n_equipo VALUES ( '21', '21', 'es', 'Nigeria' );
 INSERT INTO i18n_equipo VALUES ( '22', '22', 'es', 'Panama' );
 INSERT INTO i18n_equipo VALUES ( '23', '23', 'es', 'Peru' );
 INSERT INTO i18n_equipo VALUES ( '24', '24', 'es', 'Polonia' );
 INSERT INTO i18n_equipo VALUES ( '25', '25', 'es', 'Portugal' );
 INSERT INTO i18n_equipo VALUES ( '26', '26', 'es', 'Rusia' );
 INSERT INTO i18n_equipo VALUES ( '27', '27', 'es', 'Senegal' );
 INSERT INTO i18n_equipo VALUES ( '28', '28', 'es', 'Serbia' );
 INSERT INTO i18n_equipo VALUES ( '29', '29', 'es', 'Suiza' );
 INSERT INTO i18n_equipo VALUES ( '30', '30', 'es', 'Suecia' );
 INSERT INTO i18n_equipo VALUES ( '31', '31', 'es', 'Tunez' );
 INSERT INTO i18n_equipo VALUES ( '32', '32', 'es', 'Uruguay' );
 INSERT INTO i18n_equipo VALUES ( '33', '1', 'en', 'Argentina' );
 INSERT INTO i18n_equipo VALUES ( '34', '2', 'en', 'Australia' );
 INSERT INTO i18n_equipo VALUES ( '35', '3', 'en', 'Belgium' );
 INSERT INTO i18n_equipo VALUES ( '36', '4', 'en', 'Brazil' );
 INSERT INTO i18n_equipo VALUES ( '37', '5', 'en', 'Colombia' );
 INSERT INTO i18n_equipo VALUES ( '38', '6', 'en', 'Costa Rica' );
 INSERT INTO i18n_equipo VALUES ( '39', '7', 'en', 'Croatia' );
 INSERT INTO i18n_equipo VALUES ( '40', '8', 'en', 'Denmark' );
 INSERT INTO i18n_equipo VALUES ( '41', '9', 'en', 'Egypt' );
 INSERT INTO i18n_equipo VALUES ( '42', '10', 'en', 'England' );
 INSERT INTO i18n_equipo VALUES ( '43', '11', 'en', 'Spaid' );
 INSERT INTO i18n_equipo VALUES ( '44', '12', 'en', 'France' );
 INSERT INTO i18n_equipo VALUES ( '45', '13', 'en', 'Germany' );
 INSERT INTO i18n_equipo VALUES ( '46', '14', 'en', 'Iran' );
 INSERT INTO i18n_equipo VALUES ( '47', '15', 'en', 'Iceland' );
 INSERT INTO i18n_equipo VALUES ( '48', '16', 'en', 'Japan' );
 INSERT INTO i18n_equipo VALUES ( '49', '17', 'en', 'Korea' );
 INSERT INTO i18n_equipo VALUES ( '50', '18', 'en', 'Saudi Arabia' );
 INSERT INTO i18n_equipo VALUES ( '51', '19', 'en', 'Morocco' );
 INSERT INTO i18n_equipo VALUES ( '52', '20', 'en', 'Mexico' );
 INSERT INTO i18n_equipo VALUES ( '53', '21', 'en', 'Nigeria' );
 INSERT INTO i18n_equipo VALUES ( '54', '22', 'en', 'Panama' );
 INSERT INTO i18n_equipo VALUES ( '55', '23', 'en', 'Peru' );
 INSERT INTO i18n_equipo VALUES ( '56', '24', 'en', 'Poland' );
 INSERT INTO i18n_equipo VALUES ( '57', '25', 'en', 'Portugal' );
 INSERT INTO i18n_equipo VALUES ( '58', '26', 'en', 'Russia' );
 INSERT INTO i18n_equipo VALUES ( '59', '27', 'en', 'Senegal' );
 INSERT INTO i18n_equipo VALUES ( '60', '28', 'en', 'Serbia' );
 INSERT INTO i18n_equipo VALUES ( '61', '29', 'en', 'Switzerland' );
 INSERT INTO i18n_equipo VALUES ( '62', '30', 'en', 'Sweden' );
 INSERT INTO i18n_equipo VALUES ( '63', '31', 'en', 'Tunisia' );
 INSERT INTO i18n_equipo VALUES ( '64', '32', 'en', 'Uruguay' );


 
 INSERT INTO PAIS VALUES ( 'ARG', '1', '' );
 INSERT INTO PAIS VALUES ( 'AUS', '2', '' );
 INSERT INTO PAIS VALUES ( 'BEL', '3', '' );
 INSERT INTO PAIS VALUES ( 'BRA', '4', '' );
 INSERT INTO PAIS VALUES ( 'COL', '5', '' );
 INSERT INTO PAIS VALUES ( 'CRC', '6', '' );
 INSERT INTO PAIS VALUES ( 'CRO', '7', '' );
 INSERT INTO PAIS VALUES ( 'DEN', '8', '' );
 INSERT INTO PAIS VALUES ( 'EGY', '9', '' );
 INSERT INTO PAIS VALUES ( 'END', '10', '' );
 INSERT INTO PAIS VALUES ( 'ESP', '11', '' );
 INSERT INTO PAIS VALUES ( 'FRA', '12', '' );
 INSERT INTO PAIS VALUES ( 'GER', '13', '' );
 INSERT INTO PAIS VALUES ( 'IRN', '14', '' );
 INSERT INTO PAIS VALUES ( 'ISL', '15', '' );
 INSERT INTO PAIS VALUES ( 'JPN', '16', '' );
 INSERT INTO PAIS VALUES ( 'KON', '17', '' );
 INSERT INTO PAIS VALUES ( 'KSA', '18', '' );
 INSERT INTO PAIS VALUES ( 'MAR', '19', '' );
 INSERT INTO PAIS VALUES ( 'MEX', '20', '' );
 INSERT INTO PAIS VALUES ( 'NGA', '21', '' );
 INSERT INTO PAIS VALUES ( 'PAN', '22', '' );
 INSERT INTO PAIS VALUES ( 'PER', '23', '' );
 INSERT INTO PAIS VALUES ( 'POL', '24', '' );
 INSERT INTO PAIS VALUES ( 'POR', '25', '' );
 INSERT INTO PAIS VALUES ( 'RUS', '26', '' );
 INSERT INTO PAIS VALUES ( 'SEN', '27', '' );
 INSERT INTO PAIS VALUES ( 'SRB', '28', '' );
 INSERT INTO PAIS VALUES ( 'SUI', '29', '' );
 INSERT INTO PAIS VALUES ( 'SWE', '30', '' );
 INSERT INTO PAIS VALUES ( 'TUN', '31', '' );
 INSERT INTO PAIS VALUES ( 'URU', '32', '' );

