/*COLOCAR INSERTS EN CASO DE SER NECEARIO PARA HACER PRUEBAS */

 INSERT INTO i18n_equipo VALUES ( nextval('seq_i18n_equipo'), '1', 'es', 'Argentina' );
 INSERT INTO i18n_equipo VALUES ( nextval('seq_i18n_equipo'), '2', 'es', 'Australia' );
 INSERT INTO i18n_equipo VALUES ( nextval('seq_i18n_equipo'), '3', 'es', 'Belgica' );
 INSERT INTO i18n_equipo VALUES ( nextval('seq_i18n_equipo'), '4', 'es', 'Brasil' );
 INSERT INTO i18n_equipo VALUES ( nextval('seq_i18n_equipo'), '5', 'es', 'Colombia' );
 INSERT INTO i18n_equipo VALUES ( nextval('seq_i18n_equipo'), '6', 'es', 'Costa Rica' );
 INSERT INTO i18n_equipo VALUES ( nextval('seq_i18n_equipo'), '7', 'es', 'Croacia' );
 INSERT INTO i18n_equipo VALUES ( nextval('seq_i18n_equipo'), '8', 'es', 'Dinamarca' );
 INSERT INTO i18n_equipo VALUES ( nextval('seq_i18n_equipo'), '9', 'es', 'Egypto' );
 INSERT INTO i18n_equipo VALUES ( nextval('seq_i18n_equipo'), '10', 'es', 'Inglaterra' );
 INSERT INTO i18n_equipo VALUES ( nextval('seq_i18n_equipo'), '11', 'es', 'España' );
 INSERT INTO i18n_equipo VALUES ( nextval('seq_i18n_equipo'), '12', 'es', 'Francia' );
 INSERT INTO i18n_equipo VALUES ( nextval('seq_i18n_equipo'), '13', 'es', 'Alemania' );
 INSERT INTO i18n_equipo VALUES ( nextval('seq_i18n_equipo'), '14', 'es', 'Iran' );
 INSERT INTO i18n_equipo VALUES ( nextval('seq_i18n_equipo'), '15', 'es', 'Islandia' );
 INSERT INTO i18n_equipo VALUES ( nextval('seq_i18n_equipo'), '16', 'es', 'Japon' );
 INSERT INTO i18n_equipo VALUES ( nextval('seq_i18n_equipo'), '17', 'es', 'Korea' );
 INSERT INTO i18n_equipo VALUES ( nextval('seq_i18n_equipo'), '18', 'es', 'Arabia Saudita' );
 INSERT INTO i18n_equipo VALUES ( nextval('seq_i18n_equipo'), '19', 'es', 'Marruecos' );
 INSERT INTO i18n_equipo VALUES ( nextval('seq_i18n_equipo'), '20', 'es', 'Mexico' );
 INSERT INTO i18n_equipo VALUES ( nextval('seq_i18n_equipo'), '21', 'es', 'Nigeria' );
 INSERT INTO i18n_equipo VALUES ( nextval('seq_i18n_equipo'), '22', 'es', 'Panama' );
 INSERT INTO i18n_equipo VALUES ( nextval('seq_i18n_equipo'), '23', 'es', 'Peru' );
 INSERT INTO i18n_equipo VALUES ( nextval('seq_i18n_equipo'), '24', 'es', 'Polonia' );
 INSERT INTO i18n_equipo VALUES ( nextval('seq_i18n_equipo'), '25', 'es', 'Portugal' );
 INSERT INTO i18n_equipo VALUES ( nextval('seq_i18n_equipo'), '26', 'es', 'Rusia' );
 INSERT INTO i18n_equipo VALUES ( nextval('seq_i18n_equipo'), '27', 'es', 'Senegal' );
 INSERT INTO i18n_equipo VALUES ( nextval('seq_i18n_equipo'), '28', 'es', 'Serbia' );
 INSERT INTO i18n_equipo VALUES ( nextval('seq_i18n_equipo'), '29', 'es', 'Suiza' );
 INSERT INTO i18n_equipo VALUES ( nextval('seq_i18n_equipo'), '30', 'es', 'Suecia' );
 INSERT INTO i18n_equipo VALUES ( nextval('seq_i18n_equipo'), '31', 'es', 'Tunez' );
 INSERT INTO i18n_equipo VALUES ( nextval('seq_i18n_equipo'), '32', 'es', 'Uruguay' );
 INSERT INTO i18n_equipo VALUES ( nextval('seq_i18n_equipo'), '1', 'en', 'Argentina' );
 INSERT INTO i18n_equipo VALUES ( nextval('seq_i18n_equipo'), '2', 'en', 'Australia' );
 INSERT INTO i18n_equipo VALUES ( nextval('seq_i18n_equipo'), '3', 'en', 'Belgium' );
 INSERT INTO i18n_equipo VALUES ( nextval('seq_i18n_equipo'), '4', 'en', 'Brazil' );
 INSERT INTO i18n_equipo VALUES ( nextval('seq_i18n_equipo'), '5', 'en', 'Colombia' );
 INSERT INTO i18n_equipo VALUES ( nextval('seq_i18n_equipo'), '6', 'en', 'Costa Rica' );
 INSERT INTO i18n_equipo VALUES ( nextval('seq_i18n_equipo'), '7', 'en', 'Croatia' );
 INSERT INTO i18n_equipo VALUES ( nextval('seq_i18n_equipo'), '8', 'en', 'Denmark' );
 INSERT INTO i18n_equipo VALUES ( nextval('seq_i18n_equipo'), '9', 'en', 'Egypt' );
 INSERT INTO i18n_equipo VALUES ( nextval('seq_i18n_equipo'), '10', 'en', 'England' );
 INSERT INTO i18n_equipo VALUES ( nextval('seq_i18n_equipo'), '11', 'en', 'Spaid' );
 INSERT INTO i18n_equipo VALUES ( nextval('seq_i18n_equipo'), '12', 'en', 'France' );
 INSERT INTO i18n_equipo VALUES ( nextval('seq_i18n_equipo'), '13', 'en', 'Germany' );
 INSERT INTO i18n_equipo VALUES ( nextval('seq_i18n_equipo'), '14', 'en', 'Iran' );
 INSERT INTO i18n_equipo VALUES ( nextval('seq_i18n_equipo'), '15', 'en', 'Iceland' );
 INSERT INTO i18n_equipo VALUES ( nextval('seq_i18n_equipo'), '16', 'en', 'Japan' );
 INSERT INTO i18n_equipo VALUES ( nextval('seq_i18n_equipo'), '17', 'en', 'Korea' );
 INSERT INTO i18n_equipo VALUES ( nextval('seq_i18n_equipo'), '18', 'en', 'Saudi Arabia' );
 INSERT INTO i18n_equipo VALUES ( nextval('seq_i18n_equipo'), '19', 'en', 'Morocco' );
 INSERT INTO i18n_equipo VALUES ( nextval('seq_i18n_equipo'), '20', 'en', 'Mexico' );
 INSERT INTO i18n_equipo VALUES ( nextval('seq_i18n_equipo'), '21', 'en', 'Nigeria' );
 INSERT INTO i18n_equipo VALUES ( nextval('seq_i18n_equipo'), '22', 'en', 'Panama' );
 INSERT INTO i18n_equipo VALUES ( nextval('seq_i18n_equipo'), '23', 'en', 'Peru' );
 INSERT INTO i18n_equipo VALUES ( nextval('seq_i18n_equipo'), '24', 'en', 'Poland' );
 INSERT INTO i18n_equipo VALUES ( nextval('seq_i18n_equipo'), '25', 'en', 'Portugal' );
 INSERT INTO i18n_equipo VALUES ( nextval('seq_i18n_equipo'), '26', 'en', 'Russia' );
 INSERT INTO i18n_equipo VALUES ( nextval('seq_i18n_equipo'), '27', 'en', 'Senegal' );
 INSERT INTO i18n_equipo VALUES ( nextval('seq_i18n_equipo'), '28', 'en', 'Serbia' );
 INSERT INTO i18n_equipo VALUES ( nextval('seq_i18n_equipo'), '29', 'en', 'Switzerland' );
 INSERT INTO i18n_equipo VALUES ( nextval('seq_i18n_equipo'), '30', 'en', 'Sweden' );
 INSERT INTO i18n_equipo VALUES ( nextval('seq_i18n_equipo'), '31', 'en', 'Tunisia' );
 INSERT INTO i18n_equipo VALUES ( nextval('seq_i18n_equipo'), '32', 'en', 'Uruguay' );


 
 INSERT INTO PAIS VALUES ( 'ARG', '1', '' );
 INSERT INTO PAIS VALUES ( 'AUS', '2', '' );
 INSERT INTO PAIS VALUES ( 'BEL', '3', '' );
 INSERT INTO PAIS VALUES ( 'BRA', '4', '' );
 INSERT INTO PAIS VALUES ( 'COL', '5', '' );
 INSERT INTO PAIS VALUES ( 'CRC', '6', '' );
 INSERT INTO PAIS VALUES ( 'CRO', '7', '' );
 INSERT INTO PAIS VALUES ( 'DEN', '8', '' );
 INSERT INTO PAIS VALUES ( 'EGY', '9', '' );
 INSERT INTO PAIS VALUES ( 'END', '10', '' );
 INSERT INTO PAIS VALUES ( 'ESP', '11', '' );
 INSERT INTO PAIS VALUES ( 'FRA', '12', '' );
 INSERT INTO PAIS VALUES ( 'GER', '13', '' );
 INSERT INTO PAIS VALUES ( 'IRN', '14', '' );
 INSERT INTO PAIS VALUES ( 'ISL', '15', '' );
 INSERT INTO PAIS VALUES ( 'JPN', '16', '' );
 INSERT INTO PAIS VALUES ( 'KON', '17', '' );
 INSERT INTO PAIS VALUES ( 'KSA', '18', '' );
 INSERT INTO PAIS VALUES ( 'MAR', '19', '' );
 INSERT INTO PAIS VALUES ( 'MEX', '20', '' );
 INSERT INTO PAIS VALUES ( 'NGA', '21', '' );
 INSERT INTO PAIS VALUES ( 'PAN', '22', '' );
 INSERT INTO PAIS VALUES ( 'PER', '23', '' );
 INSERT INTO PAIS VALUES ( 'POL', '24', '' );
 INSERT INTO PAIS VALUES ( 'POR', '25', '' );
 INSERT INTO PAIS VALUES ( 'RUS', '26', '' );
 INSERT INTO PAIS VALUES ( 'SEN', '27', '' );
 INSERT INTO PAIS VALUES ( 'SRB', '28', '' );
 INSERT INTO PAIS VALUES ( 'SUI', '29', '' );
 INSERT INTO PAIS VALUES ( 'SWE', '30', '' );
 INSERT INTO PAIS VALUES ( 'TUN', '31', '' );
 INSERT INTO PAIS VALUES ( 'URU', '32', '' );